/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package curreny.exchange;

import java.math.BigDecimal;

public class Main {
    public static void main(String[] args) {

        try {
            CurrencyExchangeSystem ces = new CurrencyExchangeSystem();
            BigDecimal value = ces.currencyExchange("GBP", "PKR", 10.45);
            System.out.println(value);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}