/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package curreny.exchange;

import java.sql.SQLException;

public class Main {
    public static void main(String[] args) {

        try {
            CurrencyExchangeSystem ces = new CurrencyExchangeSystem();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
       
    }
}